[package]
name = "sntPings"
version = "0.1.0"
edition = "2021"

[dependencies]
figlet-rs = "0.1.5"
image = "0.25.4"
imageproc = "0.25.0"
pnet = "0.35.0"
rand = "0.8.5"
reqwest = { version = "0.12.9", features = ["blocking", "json"] }
serde_json = "1.0.132"
